name: Validate
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: pnpm/action-setup@v6.1.0
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm build
      - run: pnpm test:integration
      - run: pnpm exec playwright install --with-deps chromium
      - run: pnpm test:browser
      - run: pnpm deploy:check
